version: "3"
services:
    database:
        image: mysql
        container_name: "mysql"
        restart: always
        ports:
            - "3306:3006"
        environment:
            MYSQL_DATABASE: "mysql_seed"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: ""
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        restart: always
        environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        volumes:
        - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null


    backend:
        image: node:6.11.3
        container_name: mysql_seed
        restart: always
        volumes:
            - .:/backend
            - /node_modules
        ports:
            - 3000:3000
        command: bash -c "cd /backend && node_modules/.bin/nodemon"
